apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-irrigation

resources:
  - namespace.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - irrigation-service/deployment.yaml
  - irrigation-service/service.yaml
  - forecasting-service/deployment.yaml
  - forecasting-service/service.yaml
  - optimization-service/deployment.yaml
  - optimization-service/service.yaml

commonLabels:
  app.kubernetes.io/part-of: smart-irrigation-system
