apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-irrigation-prod

resources:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: auth-service
    count: 3
  - name: irrigation-service
    count: 3
  - name: forecasting-service
    count: 3
  - name: optimization-service
    count: 3
